import Head from 'next/head'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Homepage from '../components/Homepage'
import Categories from '../components/Categories'
import { sanityClient, urlFor } from "../sanity";
import { Post } from "../typings";
import Link from 'next/link'

interface Props {
  posts: [Post]
}


export default function Home({ posts }: Props) {
  return (
    <div className=''>
      <Head>
        <title>Blog Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        {/* <Homepage /> */}
        <div className="container mx-auto md:px-20 py-10">
      <h1 className="font-bold text-4xl py-12 text-center">Latest Posts</h1>

      {/* grid columns */}
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-14">
        {posts.map((post) => (
          <Link key={post._id} href={`/post/${post.slug.current}`}>
            <div className="group border rounded-lg cursor-pointer overflow-hidden">
              <img
                className="h-60 object-cover w-full group-hover:scale-105 transition-transform duration-200 ease-in-out"
                src={urlFor(post.mainImage).url()!}
                alt=""
              />
              <div className="flex justify-between p-5 bg-white text-black">
                <div>
                  <p className="font-bold text-lg">{post.title}</p>
                  <p className="text-xs">
                    {post.description} by {post.author.name}
                  </p>
                </div>

                <img
                  className="h-12 w-12 rounded-full"
                  src={urlFor(post.author.image).url()!}
                  alt=""
                />
              </div>
            </div>
          </Link>
        ))}
      </div>
    </div>
        <Categories />
      </main>
      <Footer />

    </div>
      
  )
}

export const getServerSideProps = async () => {
  const query = `*[_type == "post"]{
    _id,
    title,
   author -> {
   name,
   image
 },
 description,
 mainImage,
 slug
  }`;

  const posts = await sanityClient.fetch(query);
  return {
    props: {
      posts,
    },
  };
};

